### ISSUE TITLE
data_mesh_util\lib\utils.py - AttributeError: 'Session' object has no attribute 'client'

### ISSUE THREAD

**Issue by danrosenfe** [aws-samples/aws-data-mesh-utils#1]
First of all I would like to say that we are very grateful for this great contribution, thank you!

I may be doing something wrong because I had a problem performing the step "Step 1.0 - Install the data mesh":

**first** - error:   use_creds=credentials TypeError: __init__() got an unexpected keyword argument '**use_creds**'.
**second** - After seeing the class declaration in DataMeshAdmin.py replace **use_creds** by **use_credentialss** and rerun, prem I had a new problem

"....data_mesh_util\lib\utils.py", line 249, in generate_client
    return session.client(service)
**AttributeError: 'Session' object has no attribute 'client'**

I apologize if this is a beginner's question.

I tried running examples/0_setup_central_account.py example and got to the same point

**Comment by IanMeyers** [comment]
What version of boto3 are you using?

**Comment by danrosenfe** [comment]
Thanks for the tip Ian!
I change the version of
- boto3 from 1.17.112 to 1.17.34
- botocore from 1.20.112 to 1.20.34

In step 1.1 I still needed to replace use_creds with use_credentials and ran. It worked well for me!

Thank you very much

**Comment by IanMeyers** [comment]
cleaning up the docs to fix the bug in `use_creds`. Thanks!
