### ISSUE TITLE
Step 2 IAM problem from readme file

### ISSUE THREAD

**Issue by bpatoul** [aws-samples/aws-data-mesh-utils#3]
Hello,

First of all, thank you for this data mesh repository and the hard work behind. I have been testing the manual step by step from the readme file and I am facing some issues:

1. I faced this error while running the step 2: 
`botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the CreateCrawler operation: User: arn:aws:sts::753878601211:assumed-role/DataMeshProducer/AIDA27BVKRX56JUXBMRWP-753878601211-2022-02-03 is not authorized to perform: iam:PassRole on resource: arn:aws:iam::753878601211:role/service-role/AWSGlueServiceRole-datamesh because no identity-based policy allows the iam:PassRole action`

I sorted it by manually adding the iam:PassRole to the user. 

Also, in my humble opinion, I would recommend to clearly say that it is a list to pass for the tables variable in step 3 since I had the same issue in terms of passing a string.

**Comment by IanMeyers** [comment]
That is correct - if you want to use Crawler Roles, then these roles must also have granted you iam::PassRole. In version 1.0.4 additional handling has been added to make lists correctly handled even if they are encoded as csv values.
